// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: amneziawg.proto

package amneziawgv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/thebeyond-net/node-agent/pkg/amneziawg/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AmneziaWGServiceName is the fully-qualified name of the AmneziaWGService service.
	AmneziaWGServiceName = "amneziawg.v1.AmneziaWGService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AmneziaWGServiceCreatePeerProcedure is the fully-qualified name of the AmneziaWGService's
	// CreatePeer RPC.
	AmneziaWGServiceCreatePeerProcedure = "/amneziawg.v1.AmneziaWGService/CreatePeer"
	// AmneziaWGServiceDeletePeerProcedure is the fully-qualified name of the AmneziaWGService's
	// DeletePeer RPC.
	AmneziaWGServiceDeletePeerProcedure = "/amneziawg.v1.AmneziaWGService/DeletePeer"
)

// AmneziaWGServiceClient is a client for the amneziawg.v1.AmneziaWGService service.
type AmneziaWGServiceClient interface {
	CreatePeer(context.Context, *v1.CreatePeerRequest) (*v1.CreatePeerResponse, error)
	DeletePeer(context.Context, *v1.DeletePeerRequest) (*v1.DeletePeerResponse, error)
}

// NewAmneziaWGServiceClient constructs a client for the amneziawg.v1.AmneziaWGService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAmneziaWGServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AmneziaWGServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	amneziaWGServiceMethods := v1.File_amneziawg_proto.Services().ByName("AmneziaWGService").Methods()
	return &amneziaWGServiceClient{
		createPeer: connect.NewClient[v1.CreatePeerRequest, v1.CreatePeerResponse](
			httpClient,
			baseURL+AmneziaWGServiceCreatePeerProcedure,
			connect.WithSchema(amneziaWGServiceMethods.ByName("CreatePeer")),
			connect.WithClientOptions(opts...),
		),
		deletePeer: connect.NewClient[v1.DeletePeerRequest, v1.DeletePeerResponse](
			httpClient,
			baseURL+AmneziaWGServiceDeletePeerProcedure,
			connect.WithSchema(amneziaWGServiceMethods.ByName("DeletePeer")),
			connect.WithClientOptions(opts...),
		),
	}
}

// amneziaWGServiceClient implements AmneziaWGServiceClient.
type amneziaWGServiceClient struct {
	createPeer *connect.Client[v1.CreatePeerRequest, v1.CreatePeerResponse]
	deletePeer *connect.Client[v1.DeletePeerRequest, v1.DeletePeerResponse]
}

// CreatePeer calls amneziawg.v1.AmneziaWGService.CreatePeer.
func (c *amneziaWGServiceClient) CreatePeer(ctx context.Context, req *v1.CreatePeerRequest) (*v1.CreatePeerResponse, error) {
	response, err := c.createPeer.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeletePeer calls amneziawg.v1.AmneziaWGService.DeletePeer.
func (c *amneziaWGServiceClient) DeletePeer(ctx context.Context, req *v1.DeletePeerRequest) (*v1.DeletePeerResponse, error) {
	response, err := c.deletePeer.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// AmneziaWGServiceHandler is an implementation of the amneziawg.v1.AmneziaWGService service.
type AmneziaWGServiceHandler interface {
	CreatePeer(context.Context, *v1.CreatePeerRequest) (*v1.CreatePeerResponse, error)
	DeletePeer(context.Context, *v1.DeletePeerRequest) (*v1.DeletePeerResponse, error)
}

// NewAmneziaWGServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAmneziaWGServiceHandler(svc AmneziaWGServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	amneziaWGServiceMethods := v1.File_amneziawg_proto.Services().ByName("AmneziaWGService").Methods()
	amneziaWGServiceCreatePeerHandler := connect.NewUnaryHandlerSimple(
		AmneziaWGServiceCreatePeerProcedure,
		svc.CreatePeer,
		connect.WithSchema(amneziaWGServiceMethods.ByName("CreatePeer")),
		connect.WithHandlerOptions(opts...),
	)
	amneziaWGServiceDeletePeerHandler := connect.NewUnaryHandlerSimple(
		AmneziaWGServiceDeletePeerProcedure,
		svc.DeletePeer,
		connect.WithSchema(amneziaWGServiceMethods.ByName("DeletePeer")),
		connect.WithHandlerOptions(opts...),
	)
	return "/amneziawg.v1.AmneziaWGService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AmneziaWGServiceCreatePeerProcedure:
			amneziaWGServiceCreatePeerHandler.ServeHTTP(w, r)
		case AmneziaWGServiceDeletePeerProcedure:
			amneziaWGServiceDeletePeerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAmneziaWGServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAmneziaWGServiceHandler struct{}

func (UnimplementedAmneziaWGServiceHandler) CreatePeer(context.Context, *v1.CreatePeerRequest) (*v1.CreatePeerResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("amneziawg.v1.AmneziaWGService.CreatePeer is not implemented"))
}

func (UnimplementedAmneziaWGServiceHandler) DeletePeer(context.Context, *v1.DeletePeerRequest) (*v1.DeletePeerResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("amneziawg.v1.AmneziaWGService.DeletePeer is not implemented"))
}
