// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: amneziawg.proto

package amneziawgv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/thebeyond-net/node-agent/pkg/amneziawg/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AmneziaWGServiceName is the fully-qualified name of the AmneziaWGService service.
	AmneziaWGServiceName = "amneziawg.v1.AmneziaWGService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AmneziaWGServiceCreateClientProcedure is the fully-qualified name of the AmneziaWGService's
	// CreateClient RPC.
	AmneziaWGServiceCreateClientProcedure = "/amneziawg.v1.AmneziaWGService/CreateClient"
	// AmneziaWGServiceDeleteClientProcedure is the fully-qualified name of the AmneziaWGService's
	// DeleteClient RPC.
	AmneziaWGServiceDeleteClientProcedure = "/amneziawg.v1.AmneziaWGService/DeleteClient"
)

// AmneziaWGServiceClient is a client for the amneziawg.v1.AmneziaWGService service.
type AmneziaWGServiceClient interface {
	CreateClient(context.Context, *v1.CreateClientRequest) (*v1.CreateClientResponse, error)
	DeleteClient(context.Context, *v1.DeleteClientRequest) (*v1.DeleteClientResponse, error)
}

// NewAmneziaWGServiceClient constructs a client for the amneziawg.v1.AmneziaWGService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAmneziaWGServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AmneziaWGServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	amneziaWGServiceMethods := v1.File_amneziawg_proto.Services().ByName("AmneziaWGService").Methods()
	return &amneziaWGServiceClient{
		createClient: connect.NewClient[v1.CreateClientRequest, v1.CreateClientResponse](
			httpClient,
			baseURL+AmneziaWGServiceCreateClientProcedure,
			connect.WithSchema(amneziaWGServiceMethods.ByName("CreateClient")),
			connect.WithClientOptions(opts...),
		),
		deleteClient: connect.NewClient[v1.DeleteClientRequest, v1.DeleteClientResponse](
			httpClient,
			baseURL+AmneziaWGServiceDeleteClientProcedure,
			connect.WithSchema(amneziaWGServiceMethods.ByName("DeleteClient")),
			connect.WithClientOptions(opts...),
		),
	}
}

// amneziaWGServiceClient implements AmneziaWGServiceClient.
type amneziaWGServiceClient struct {
	createClient *connect.Client[v1.CreateClientRequest, v1.CreateClientResponse]
	deleteClient *connect.Client[v1.DeleteClientRequest, v1.DeleteClientResponse]
}

// CreateClient calls amneziawg.v1.AmneziaWGService.CreateClient.
func (c *amneziaWGServiceClient) CreateClient(ctx context.Context, req *v1.CreateClientRequest) (*v1.CreateClientResponse, error) {
	response, err := c.createClient.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteClient calls amneziawg.v1.AmneziaWGService.DeleteClient.
func (c *amneziaWGServiceClient) DeleteClient(ctx context.Context, req *v1.DeleteClientRequest) (*v1.DeleteClientResponse, error) {
	response, err := c.deleteClient.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// AmneziaWGServiceHandler is an implementation of the amneziawg.v1.AmneziaWGService service.
type AmneziaWGServiceHandler interface {
	CreateClient(context.Context, *v1.CreateClientRequest) (*v1.CreateClientResponse, error)
	DeleteClient(context.Context, *v1.DeleteClientRequest) (*v1.DeleteClientResponse, error)
}

// NewAmneziaWGServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAmneziaWGServiceHandler(svc AmneziaWGServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	amneziaWGServiceMethods := v1.File_amneziawg_proto.Services().ByName("AmneziaWGService").Methods()
	amneziaWGServiceCreateClientHandler := connect.NewUnaryHandlerSimple(
		AmneziaWGServiceCreateClientProcedure,
		svc.CreateClient,
		connect.WithSchema(amneziaWGServiceMethods.ByName("CreateClient")),
		connect.WithHandlerOptions(opts...),
	)
	amneziaWGServiceDeleteClientHandler := connect.NewUnaryHandlerSimple(
		AmneziaWGServiceDeleteClientProcedure,
		svc.DeleteClient,
		connect.WithSchema(amneziaWGServiceMethods.ByName("DeleteClient")),
		connect.WithHandlerOptions(opts...),
	)
	return "/amneziawg.v1.AmneziaWGService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AmneziaWGServiceCreateClientProcedure:
			amneziaWGServiceCreateClientHandler.ServeHTTP(w, r)
		case AmneziaWGServiceDeleteClientProcedure:
			amneziaWGServiceDeleteClientHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAmneziaWGServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAmneziaWGServiceHandler struct{}

func (UnimplementedAmneziaWGServiceHandler) CreateClient(context.Context, *v1.CreateClientRequest) (*v1.CreateClientResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("amneziawg.v1.AmneziaWGService.CreateClient is not implemented"))
}

func (UnimplementedAmneziaWGServiceHandler) DeleteClient(context.Context, *v1.DeleteClientRequest) (*v1.DeleteClientResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("amneziawg.v1.AmneziaWGService.DeleteClient is not implemented"))
}
