// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: amneziawg.proto

package amneziawgv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	mi := &file_amneziawg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amneziawg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_amneziawg_proto_rawDescGZIP(), []int{0}
}

type CreateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Config        string                 `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Pubkey        string                 `protobuf:"bytes,4,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientResponse) Reset() {
	*x = CreateClientResponse{}
	mi := &file_amneziawg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientResponse) ProtoMessage() {}

func (x *CreateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amneziawg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientResponse.ProtoReflect.Descriptor instead.
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return file_amneziawg_proto_rawDescGZIP(), []int{1}
}

func (x *CreateClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateClientResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateClientResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *CreateClientResponse) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

type DeleteClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        string                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientRequest) Reset() {
	*x = DeleteClientRequest{}
	mi := &file_amneziawg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientRequest) ProtoMessage() {}

func (x *DeleteClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amneziawg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientRequest.ProtoReflect.Descriptor instead.
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return file_amneziawg_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteClientRequest) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

type DeleteClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientResponse) Reset() {
	*x = DeleteClientResponse{}
	mi := &file_amneziawg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientResponse) ProtoMessage() {}

func (x *DeleteClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amneziawg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientResponse.ProtoReflect.Descriptor instead.
func (*DeleteClientResponse) Descriptor() ([]byte, []int) {
	return file_amneziawg_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteClientResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_amneziawg_proto protoreflect.FileDescriptor

const file_amneziawg_proto_rawDesc = "" +
	"\n" +
	"\x0famneziawg.proto\x12\famneziawg.v1\"\x15\n" +
	"\x13CreateClientRequest\"v\n" +
	"\x14CreateClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06config\x18\x03 \x01(\tR\x06config\x12\x16\n" +
	"\x06pubkey\x18\x04 \x01(\tR\x06pubkey\"-\n" +
	"\x13DeleteClientRequest\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\"F\n" +
	"\x14DeleteClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xc0\x01\n" +
	"\x10AmneziaWGService\x12U\n" +
	"\fCreateClient\x12!.amneziawg.v1.CreateClientRequest\x1a\".amneziawg.v1.CreateClientResponse\x12U\n" +
	"\fDeleteClient\x12!.amneziawg.v1.DeleteClientRequest\x1a\".amneziawg.v1.DeleteClientResponseB\xb5\x01\n" +
	"\x10com.amneziawg.v1B\x0eAmneziawgProtoP\x01Z@github.com/thebeyond-net/node-agent/pkg/amneziawg/v1;amneziawgv1\xa2\x02\x03AXX\xaa\x02\fAmneziawg.V1\xca\x02\fAmneziawg\\V1\xe2\x02\x18Amneziawg\\V1\\GPBMetadata\xea\x02\rAmneziawg::V1b\x06proto3"

var (
	file_amneziawg_proto_rawDescOnce sync.Once
	file_amneziawg_proto_rawDescData []byte
)

func file_amneziawg_proto_rawDescGZIP() []byte {
	file_amneziawg_proto_rawDescOnce.Do(func() {
		file_amneziawg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amneziawg_proto_rawDesc), len(file_amneziawg_proto_rawDesc)))
	})
	return file_amneziawg_proto_rawDescData
}

var file_amneziawg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_amneziawg_proto_goTypes = []any{
	(*CreateClientRequest)(nil),  // 0: amneziawg.v1.CreateClientRequest
	(*CreateClientResponse)(nil), // 1: amneziawg.v1.CreateClientResponse
	(*DeleteClientRequest)(nil),  // 2: amneziawg.v1.DeleteClientRequest
	(*DeleteClientResponse)(nil), // 3: amneziawg.v1.DeleteClientResponse
}
var file_amneziawg_proto_depIdxs = []int32{
	0, // 0: amneziawg.v1.AmneziaWGService.CreateClient:input_type -> amneziawg.v1.CreateClientRequest
	2, // 1: amneziawg.v1.AmneziaWGService.DeleteClient:input_type -> amneziawg.v1.DeleteClientRequest
	1, // 2: amneziawg.v1.AmneziaWGService.CreateClient:output_type -> amneziawg.v1.CreateClientResponse
	3, // 3: amneziawg.v1.AmneziaWGService.DeleteClient:output_type -> amneziawg.v1.DeleteClientResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_amneziawg_proto_init() }
func file_amneziawg_proto_init() {
	if File_amneziawg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amneziawg_proto_rawDesc), len(file_amneziawg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_amneziawg_proto_goTypes,
		DependencyIndexes: file_amneziawg_proto_depIdxs,
		MessageInfos:      file_amneziawg_proto_msgTypes,
	}.Build()
	File_amneziawg_proto = out.File
	file_amneziawg_proto_goTypes = nil
	file_amneziawg_proto_depIdxs = nil
}
